# Generated by Django 4.1.3 on 2022-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='posts',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
