# Generated by Django 4.1.3 on 2022-11-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_text_posts_breed_rename_title_posts_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
